### ISSUE TITLE
How can I find the realtime data of wind

### ISSUE THREAD

**Issue by chen1993nian** [nickcam/AnimatedEnvironmentLayer#1]
Hi,gay,your project is helpfult for me, I want to get the realtime data of wind.How can I find the realtime data of wind, can you  help me. Thanks!

**Comment by nickcam** [comment]
Hi mate, I think you can get some here - [http://nomads.ncep.noaa.gov/](http://nomads.ncep.noaa.gov/),
and possibly here [https://www.ecmwf.int/](https://www.ecmwf.int/).
I don't use them though so not exactly sure where on the sites you'd find them.
