### ISSUE TITLE
How to stretch the animation to cover entire screen ?

### ISSUE THREAD

**Issue by Shruthi48** [nickcam/AnimatedEnvironmentLayer#10]
Hi ,

At the moment the animation is visible only on part of the screen , how can I stretch it to show the animation on the entire screen ?

<img width="1438" alt="Screenshot 2021-08-11 at 7 28 47 PM" src="https://user-images.githubusercontent.com/14086294/129043103-2c6634e7-c497-4ff4-afed-c1d6a5b6bc63.png">

**Comment by nickcam** [comment]
That's odd. There's a <canvas> element that should resize to the size of the screen, this is where the particles are drawn. Go into your browser debugging tools and make sure the canvas is sized correctly, ie: the width and height style properties are being set correctly. 

If they're not, should be pretty easy to find where they're getting set and why they're not updating. I can't remember exactly where that's happening sorry.

**Comment by Shruthi48** [comment]
The canvas width and height is getting set properly but I wasn't able to figure out why isn't  the animation drawn on entire canvas. The issue is in the demo url - http://animatedenvironmentlayer.azurewebsites.net/index.html

**Comment by nickcam** [comment]
Oh right, I don't get the problem when I view the demo page. I've tried it in Chrome and Firefox. What browser are you using?

**Comment by Shruthi48** [comment]
I'm using chrome , its the same when I open it on safari 

<img width="1438" alt="Screenshot 2021-08-12 at 2 50 48 PM" src="https://user-images.githubusercontent.com/14086294/129172468-5a31cb6b-2914-41c1-8381-0b74f667310d.png">

firefox too
<img width="1283" alt="Screenshot 2021-08-12 at 3 09 06 PM" src="https://user-images.githubusercontent.com/14086294/129175345-d524bc2d-ef84-41c4-8c1f-c435894c762e.png">

**Comment by sanketkardile** [comment]
@Shruthi48 did you solved this issue?

**Comment by nickcam** [comment]
This was related to window.devicePixelRatio being greater than 1. Have catered for this in the latest commit.
