### ISSUE TITLE
Error in updated hook: "TypeError: animatedEnvironmentLayer_1.AnimatedEnvironmentLayer is not a constructor"

### ISSUE THREAD

**Issue by xqwIOS** [nickcam/AnimatedEnvironmentLayer#4]
I changed the code of file pageSetUp.js   function init: 
![WX20190702-145233](https://user-images.githubusercontent.com/25758061/60490410-107d6380-9cd9-11e9-96bb-d5e4de149bf5.png)

when i  console.log(animatedEnvironmentLayer_1) it returns  
{byId: ƒ, isDescendant: ƒ, setSelectable: ƒ}
byId: ƒ (b,f)
isDescendant: ƒ (b,h)
setSelectable: ƒ (b,h)
__proto__: Object
now . what shoud i do? thanks....

**Comment by nickcam** [comment]
Hi @xqwIOS - I'm a bit unclear as to what you're trying to do? What was the point of your update.

Also, the pageSetup.js file is generated from typescript, you'd be much better off editing the typescript file, [typescript/pageSetup.ts](https://github.com/nickcam/AnimatedEnvironmentLayer/blob/master/typescript/pageSetup.ts). You can still debug into it and set breakpoints etc. 

Just follow the Usage instructions in the readme to get the project running using typescript.

**Comment by xqwIOS** [comment]
Now I had add the windy data . to the map (my arcgis for js 4.11 ) but i found that  when I move the map  the windy and the map   load very slow and how can I change the speed of Windy . thanks . my Map only add a geojsonLayer and a featureLayer

**Comment by xqwIOS** [comment]
I  just used  animatedEnvironmentLayer.js file My project used Vue.js framework

**Comment by nickcam** [comment]
Sorry I'm not very familiar with vue.js. Are you using esri-loader to load the arcgis libraries inside of your app. If so follow the instructions in it's readme related to configuring dojo to load other libraries. [https://github.com/Esri/esri-loader#configuring-dojo](https://github.com/Esri/esri-loader#configuring-dojo).

If it's still slow it could be that your wind data is of a very high resolution. The more data, the more processing it has to do on each render. If this is the case you may need to dynamically switch out data sources depending on the current scale/zoom of your map. So for further out scales, use a lower resolution dataset, and then swap in a higher resolution one just for more detailed zoom levels. Obviously this could involve a little to a lot more data having to be fetched though.
