### ISSUE TITLE
Support FOR 3D solutions

### ISSUE THREAD

**Issue by xuezepeng** [nickcam/AnimatedEnvironmentLayer#6]
Hi, I'm learning about this, too. Have you found the SOLUTION of 3D?

**Comment by nickcam** [comment]
Hi mate, I've got no plans to try and support 3d at the moment, I don't really use this layer myself anymore. 
If you manage to come up with anything feel free to submit a PR.

**Comment by xuezepeng** [comment]
Thank you for your reply. If I have a good solution, I will upload it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nickcam/AnimatedEnvironmentLayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 上午6:21
收件人:&nbsp;"nickcam/AnimatedEnvironmentLayer"<AnimatedEnvironmentLayer@noreply.github.com&gt;;
抄送:&nbsp;"396368002"<396368002@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nickcam/AnimatedEnvironmentLayer] Support FOR 3D solutions (#6)





 
Hi mate, I've got no plans to try and support 3d at the moment, I don't really use this layer myself anymore.
 If you manage to come up with anything feel free to submit a PR.
