### ISSUE TITLE
[esri.support.LayersMixin] #add() The item being added is not a Layer or a Promise that resolves to a Layer.

### ISSUE THREAD

**Issue by Shruthi48** [nickcam/AnimatedEnvironmentLayer#9]
arcgis-js-api v4.20, I tried to integrate AnimatedEnvironmentLayer by adding compiled ael/animatedEnvironmentLayer.js and reference it like the other javascript esri amd modules. 

when I do 
```
map.add(environmentLayer)
```

I am getting the error below. Is there a way I can resolve this error?

<img width="877" alt="Screenshot 2021-08-11 at 1 03 27 PM" src="https://user-images.githubusercontent.com/14086294/128989042-f041e40e-598f-4cd8-a4bb-d6f9467e45c8.png">

**Comment by Shruthi48** [comment]
found the solution , had to add this instead

```
map.layers.add(environmentLayer);
```
the other issues were related to this.attach() not being invoked as mentioned here https://github.com/nickcam/AnimatedEnvironmentLayer/issues/8. After explicitly invoking this.attach() it started to work perfectly

**Comment by nickcam** [comment]
Ok cool. I obviously haven't upgraded it to work with later versions of the api. Glad you got it going.
